name: publish-package
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Type Check
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint

      - name: Health Check
        run: |
          yarn run clean
          yarn workspaces foreach --verbose run build:package

      - name: Publish
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn changeset status
          yarn changeset version
          . "./scripts/commit-ci-changes.sh"
          yarn changeset publish
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
